openapi: 3.0.3
info:
  title: Product and Order Management API
  version: 1.0.0
  description: API for managing products, inventory, and orders
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server
  - url: http://localhost:3000/v1
    description: Local development server

tags:
  - name: Products
    description: Product catalog operations
  - name: Orders
    description: Order management operations
  - name: Inventory
    description: Inventory management operations

paths:
  /products:
    get:
      tags:
        - Products
      summary: List all products
      description: Retrieve a paginated list of all products
      operationId: listProducts
      parameters:
        - $ref: './components.yaml#/components/parameters/PageParam'
        - $ref: './components.yaml#/components/parameters/PageSizeParam'
        - name: category
          in: query
          description: Filter by product category
          schema:
            type: string
        - name: inStock
          in: query
          description: Filter by stock availability
          schema:
            type: boolean
        - name: minPrice
          in: query
          description: Minimum price filter
          schema:
            type: number
            format: double
            minimum: 0
        - name: maxPrice
          in: query
          description: Maximum price filter
          schema:
            type: number
            format: double
            minimum: 0
        - name: search
          in: query
          description: Search term to filter products by name or description
          schema:
            type: string
        - name: sortBy
          in: query
          description: Field to sort by
          schema:
            type: string
            enum: [name, price, createdAt, updatedAt]
            default: createdAt
        - name: sortOrder
          in: query
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: './components.yaml#/components/schemas/Product'
                  metadata:
                    $ref: './components.yaml#/components/schemas/PaginationMetadata'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    post:
      tags:
        - Products
      summary: Create a new product
      description: Add a new product to the catalog
      operationId: createProduct
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - price
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 200
                description:
                  type: string
                  maxLength: 2000
                price:
                  type: number
                  format: double
                  minimum: 0
                currency:
                  type: string
                  enum: [USD, EUR, GBP, JPY, CNY]
                  default: USD
                category:
                  type: string
                inStock:
                  type: boolean
                  default: true
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Product'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './components.yaml#/components/responses/Forbidden'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

  /products/{productId}:
    get:
      tags:
        - Products
      summary: Get product by ID
      description: Retrieve a specific product by its ID
      operationId: getProductById
      parameters:
        - $ref: './components.yaml#/components/parameters/ProductIdParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Product'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    put:
      tags:
        - Products
      summary: Update product
      description: Update an existing product's information
      operationId: updateProduct
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/ProductIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 200
                description:
                  type: string
                  maxLength: 2000
                price:
                  type: number
                  format: double
                  minimum: 0
                currency:
                  type: string
                  enum: [USD, EUR, GBP, JPY, CNY]
                category:
                  type: string
                inStock:
                  type: boolean
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Product'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    delete:
      tags:
        - Products
      summary: Delete product
      description: Remove a product from the catalog
      operationId: deleteProduct
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/ProductIdParam'
      responses:
        '204':
          description: Product deleted successfully
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

  /orders:
    get:
      tags:
        - Orders
      summary: List all orders
      description: Retrieve a paginated list of all orders
      operationId: listOrders
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/PageParam'
        - $ref: './components.yaml#/components/parameters/PageSizeParam'
        - name: userId
          in: query
          description: Filter by user ID
          schema:
            type: string
            format: uuid
        - name: status
          in: query
          description: Filter by order status
          schema:
            type: string
            enum: [pending, processing, shipped, delivered, cancelled]
        - name: fromDate
          in: query
          description: Filter orders created after this date
          schema:
            type: string
            format: date-time
        - name: toDate
          in: query
          description: Filter orders created before this date
          schema:
            type: string
            format: date-time
        - name: sortBy
          in: query
          description: Field to sort by
          schema:
            type: string
            enum: [createdAt, updatedAt, totalAmount]
            default: createdAt
        - name: sortOrder
          in: query
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: './components.yaml#/components/schemas/Order'
                  metadata:
                    $ref: './components.yaml#/components/schemas/PaginationMetadata'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    post:
      tags:
        - Orders
      summary: Create a new order
      description: Place a new order
      operationId: createOrder
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - items
                - shippingAddress
              properties:
                userId:
                  type: string
                  format: uuid
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - productId
                      - quantity
                    properties:
                      productId:
                        type: string
                        format: uuid
                      quantity:
                        type: integer
                        minimum: 1
                  minItems: 1
                shippingAddress:
                  $ref: './components.yaml#/components/schemas/Address'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Order'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '404':
          description: Product not found or out of stock
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Error'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

  /orders/{orderId}:
    get:
      tags:
        - Orders
      summary: Get order by ID
      description: Retrieve a specific order by its ID
      operationId: getOrderById
      security:
        - BearerAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/OrderIdParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Order'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    patch:
      tags:
        - Orders
      summary: Update order status
      description: Update the status of an existing order
      operationId: updateOrderStatus
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/OrderIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum: [pending, processing, shipped, delivered, cancelled]
      responses:
        '200':
          description: Order status updated successfully
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Order'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    delete:
      tags:
        - Orders
      summary: Cancel order
      description: Cancel an existing order
      operationId: cancelOrder
      security:
        - BearerAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/OrderIdParam'
      responses:
        '200':
          description: Order cancelled successfully
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Order'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '403':
          description: Order cannot be cancelled
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Error'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

  /inventory/{productId}:
    get:
      tags:
        - Inventory
      summary: Get product inventory
      description: Retrieve inventory information for a specific product
      operationId: getProductInventory
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/ProductIdParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: string
                    format: uuid
                  quantity:
                    type: integer
                    minimum: 0
                  reserved:
                    type: integer
                    minimum: 0
                    description: Quantity reserved for pending orders
                  available:
                    type: integer
                    minimum: 0
                    description: Quantity available for new orders
                  lastUpdated:
                    type: string
                    format: date-time
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    put:
      tags:
        - Inventory
      summary: Update product inventory
      description: Update the inventory quantity for a specific product
      operationId: updateProductInventory
      security:
        - BearerAuth: []
        - ApiKeyAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/ProductIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - quantity
              properties:
                quantity:
                  type: integer
                  minimum: 0
                  description: New inventory quantity
      responses:
        '200':
          description: Inventory updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: string
                    format: uuid
                  quantity:
                    type: integer
                    minimum: 0
                  reserved:
                    type: integer
                    minimum: 0
                  available:
                    type: integer
                    minimum: 0
                  lastUpdated:
                    type: string
                    format: date-time
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      $ref: './components.yaml#/components/securitySchemes/BearerAuth'
    ApiKeyAuth:
      $ref: './components.yaml#/components/securitySchemes/ApiKeyAuth'
