openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0
  description: API for managing users and their profiles
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server
  - url: http://localhost:3000/v1
    description: Local development server

tags:
  - name: Users
    description: User management operations
  - name: Authentication
    description: Authentication and authorization operations

paths:
  /users:
    get:
      tags:
        - Users
      summary: List all users
      description: Retrieve a paginated list of all users
      operationId: listUsers
      security:
        - BearerAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/PageParam'
        - $ref: './components.yaml#/components/parameters/PageSizeParam'
        - name: search
          in: query
          description: Search term to filter users by username or email
          schema:
            type: string
        - name: sortBy
          in: query
          description: Field to sort by
          schema:
            type: string
            enum: [username, email, createdAt, updatedAt]
            default: createdAt
        - name: sortOrder
          in: query
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: './components.yaml#/components/schemas/User'
                  metadata:
                    $ref: './components.yaml#/components/schemas/PaginationMetadata'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    post:
      tags:
        - Users
      summary: Create a new user
      description: Create a new user account
      operationId: createUser
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 50
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                  minLength: 8
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/User'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Error'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

  /users/{userId}:
    get:
      tags:
        - Users
      summary: Get user by ID
      description: Retrieve a specific user by their ID
      operationId: getUserById
      security:
        - BearerAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/UserIdParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/User'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    put:
      tags:
        - Users
      summary: Update user
      description: Update an existing user's information
      operationId: updateUser
      security:
        - BearerAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 50
                email:
                  type: string
                  format: email
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/User'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

    delete:
      tags:
        - Users
      summary: Delete user
      description: Delete a user account
      operationId: deleteUser
      security:
        - BearerAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/UserIdParam'
      responses:
        '204':
          description: User deleted successfully
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

  /users/{userId}/orders:
    get:
      tags:
        - Users
      summary: Get user's orders
      description: Retrieve all orders for a specific user
      operationId: getUserOrders
      security:
        - BearerAuth: []
      parameters:
        - $ref: './components.yaml#/components/parameters/UserIdParam'
        - $ref: './components.yaml#/components/parameters/PageParam'
        - $ref: './components.yaml#/components/parameters/PageSizeParam'
        - name: status
          in: query
          description: Filter by order status
          schema:
            type: string
            enum: [pending, processing, shipped, delivered, cancelled]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: './components.yaml#/components/schemas/Order'
                  metadata:
                    $ref: './components.yaml#/components/schemas/PaginationMetadata'
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '404':
          $ref: './components.yaml#/components/responses/NotFound'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

  /auth/login:
    post:
      tags:
        - Authentication
      summary: User login
      description: Authenticate a user and return a JWT token
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT access token
                  refreshToken:
                    type: string
                    description: Refresh token
                  expiresIn:
                    type: integer
                    description: Token expiration time in seconds
                  user:
                    $ref: './components.yaml#/components/schemas/User'
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Error'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

  /auth/logout:
    post:
      tags:
        - Authentication
      summary: User logout
      description: Invalidate the current user's session
      operationId: logout
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Logout successful
        '401':
          $ref: './components.yaml#/components/responses/Unauthorized'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

  /auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh access token
      description: Get a new access token using a refresh token
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
                  description: Refresh token
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: New JWT access token
                  expiresIn:
                    type: integer
                    description: Token expiration time in seconds
        '400':
          $ref: './components.yaml#/components/responses/BadRequest'
        '401':
          description: Invalid refresh token
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Error'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      $ref: './components.yaml#/components/securitySchemes/BearerAuth'
